---
# tasks file for ansible-php
- name: install packages
  apt:
    pkg:
    - apt-transport-https
    - lsb-release
    - ca-certificates
    - curl
    update_cache: yes

- name: import apt php key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: install php deb repository
  apt_repository:
    repo: deb https://packages.sury.org/php/ stretch main
    state: present

- name: install php packages
  apt:
    update_cache: yes
    pkg:
    - "php{{ php_version }}"
    - "php{{ php_version }}-bcmath"
    - "php{{ php_version }}-bz2"
    - "php{{ php_version }}-cgi"
    - "php{{ php_version }}-cli"
    - "php{{ php_version }}-common"
    - "php{{ php_version }}-curl"
    - "php{{ php_version }}-dba"
    - "php{{ php_version }}-dev"
    - "php{{ php_version }}-enchant"
    - "php{{ php_version }}-fpm"
    - "php{{ php_version }}-gd"
    - "php{{ php_version }}-gmp"
    - "php{{ php_version }}-imap"
    - "php{{ php_version }}-interbase"
    - "php{{ php_version }}-intl"
    - "php{{ php_version }}-json"
    - "php{{ php_version }}-ldap"
    - "php{{ php_version }}-mbstring"
      #- "php{{ php_version }}-mcrypt"
    - "php{{ php_version }}-mysql"
    - "php{{ php_version }}-odbc"
    - "php{{ php_version }}-opcache"
    - "php{{ php_version }}-pgsql"
    - "php{{ php_version }}-phpdbg"
    - "php{{ php_version }}-pspell"
    - "php{{ php_version }}-readline"
    - "php{{ php_version }}-recode"
    - "php{{ php_version }}-snmp"
    - "php{{ php_version }}-soap"
    - "php{{ php_version }}-sqlite3"
    - "php{{ php_version }}-sybase"
    - "php{{ php_version }}-tidy"
    - "php{{ php_version }}-xml"
    - "php{{ php_version }}-xmlrpc"
    - "php{{ php_version }}-xsl"
    - "php{{ php_version }}-zip"
