all:
  hosts:
    test01:
  children:
    builder:
      hosts:
        test01:
    bcdocs:
      hosts:
        palladio:
    dev:
      hosts:
        palladio:
    prod:
      hosts:
        oxygene:
    home:
      hosts:
        rpi3:
          ansible_host: 192.168.0.3
      hosts:
        rpi4:
          ansible_host: 192.168.0.4


