---
- hosts: builder
  become: yes
  vars:
    githubuser: "{{ lookup('passwordstore', 'github/deployuser') }}"
    token: "{{ lookup('passwordstore', 'github/deploytoken') }}"
    deploy_user: ansible
  roles:
    - ansible-passwordstore
