---
# tasks file for ansible-passwordstore
- name: update apt cache
  apt: update_cache=yes
  tags:
    - installpackages

- name: install required packages
  apt:
    pkg:
    - git
    - gpg
    - pass
    - rng-tools
  tags:
    - installpackages

- name: Get passwords
  git:
    repo: "https://{{ githubuser | urlencode }}:{{ token | urlencode }}@github.com/barbearclassico/martimmoniz.git"
    version: master
    dest: /opt/keymaster/martimmoniz
    accept_hostkey: yes
  become: yes
  tags:
    - pass-workspace

- name: Test if the key exists
  become: yes
  become_user: "{{ deploy_user }}"
  raw: "gpg --list-secret-keys deployer@pulsingminds.com"
  register: gpgkeypresent
  ignore_errors: True
  tags:
  - import-key

- name: force importkey
  when: forcedeploy is defined
  set_fact:
    gpgkeypresent: failed
  tags:
  - import-key

- name: shows the key if it is present
  debug:
    msg: "{{ gpgkeypresent.stdout }}"
  tags:
  - import-key

- name: Get deployer home path
  when: gpgkeypresent is failed
  shell: "getent passwd {{ deploy_user }} | cut -d: -f6"
  register: deploy_home
  tags:
  - link

- name: Create a symbolic link to password-store
  when: gpgkeypresent is failed
  file:
    src: "/opt/keymaster/martimmoniz"
    dest: "{{ deploy_home.stdout }}/.password-store"
    owner: "{{ deploy_user }}"
    state: link
  tags:
  - link

- name: Makes gnupg folder readable
  when: gpgkeypresent is failed
  file:
    path: "{{ deploy_home.stdout }}/.gnupg"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    mode: '0666'
    recurse: yes
    state: directory
  tags:
  - import-key

- name: import defined key
  when: gpgkeypresent is failed
  shell:
    cmd: |
      export GNUPGHOME="{{ deploy_home.stdout }}/.gnupg"
      (
      cat <<EOF
      {{ lookup('passwordstore', 'bc-new/test01/gpg-priv returnall=true') }}
      EOF
      ) | gpg --allow-secret-key-import --import
  register: gpgimport
  no_log: true
  tags:
  - import-key

- name: Print gpg import output
  when: gpgkeypresent is failed
  debug:
    msg: "{{ gpgimport.stdout }}\n{{ gpgimport.stderr }}"
  tags:
  - import-key

- name: Protects gnupg from everyone
  when: gpgkeypresent is failed
  file:
    path: "{{ deploy_home.stdout }}/.gnupg"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    recurse: yes
    mode: '0700'
    state: directory
  tags:
  - import-key

